# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT
---
# https://docs.github.com/actions/learn-github-actions
# https://github.com/actions/upload-artifact
name: release
'on':
  push:
    branches:
      - main
      - dev
      - test

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

env:
  GITHUB_TOKEN: '${{ github.token }}'
  CW_MAP: '0'
  CW_JOBS: '5'
  DO_NOT_TRACK: '1'
  SIGN_PKG_KEY_ID: 'BDCF067D3908B2727A4A948767C1003740BF8DC2'

jobs:
  win:
    if: ${{ github.repository_owner == 'curl' }}
    name: 'Windows (arm64, x64, x86)'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          fetch-depth: '300'
      - name: 'build'
        env:
          SIGN_CODE_GPG_PASS: '${{ secrets.SIGN_CODE_GPG_PASS }}'
          SIGN_CODE_KEY_PASS: '${{ secrets.SIGN_CODE_KEY_PASS }}'
          SIGN_PKG_GPG_PASS: '${{ secrets.SIGN_PKG_GPG_PASS }}'
          SIGN_PKG_KEY_PASS: '${{ secrets.SIGN_PKG_KEY_PASS }}'
          COSIGN_PKG_GPG_PASS: '${{ secrets.COSIGN_PKG_GPG_PASS }}'
          COSIGN_PKG_KEY_PASS: '${{ secrets.COSIGN_PKG_KEY_PASS }}'
          DEPLOY_GPG_PASS: '${{ secrets.DEPLOY_GPG_PASS }}'
          DEPLOY_KEY_PASS: '${{ secrets.DEPLOY_KEY_PASS }}'
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '0'
        run: |
          export CW_CONFIG='werror-win'
          export CW_REVISION; CW_REVISION="$(TZ=UTC date +'%Y%m%d')"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${DOCKER_IMAGE}"
          podman images --digests
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|SIGN_|COSIGN_|GITHUB_|DEPLOY_|DO_NOT_TRACK)') \
            "${DOCKER_IMAGE}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt ./*-version-*.txt || true
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: 'curl-windows-daily-tool'
          retention-days: 180
          path: curl-*-*-*/curl*
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: 'curl-windows-daily'
          retention-days: 180
          path: |
            *-*-mingw*.*
            urls.txt
